### ISSUE TITLE
Static files

### ISSUE THREAD

**Issue by blob8108** [cambridge-alpha-team/unvisual-backend#17]
Where is Java expecting the frontend to be cloned to?

This repo claims to pull in `unvisual-frontend` as a submodule, but doesn't appear to actually do that anywhere AFAICT.

**Comment by KoviRobi** [comment]
Yes sorry that was left in from the maven stuff, but the native server will probably expect the frontend to be in src/main/resources as that way it will get packaged in the jar and could work with #18 , but for the moment you can just have it anywhere and pass it as the zeroeth argument to the jar

**Comment by blob8108** [comment]
> pass it as the zeroeth argument to the jar

Oh awesome, it works now! The Readme is a little misleading, then :)
