### ISSUE TITLE
Content types

### ISSUE THREAD

**Issue by blob8108** [cambridge-alpha-team/unvisual-backend#21]
The HTTP server should set the right content types, so Chrome doesn't complain at us.

```
var FORMATS = {
    ".css": "text/css",
    ".html": "text/html",
    ".js": "text/javascript",
  };
```

Just check the file extension, and set the `Content-Type` header with the right value.

**Comment by KoviRobi** [comment]
Thanks, done! I am only using a compiled-in map, but that should not matter as we don't expect our server to handle file types that we don't know about.

**Comment by blob8108** [comment]
Yeah, that should be fine :)
